version: "3.9"  # optional since v1.27.0
networks:
  principal:

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8080"
    volumes:
      - ./frontend:/app
    networks:
      - principal
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:80"
    command: bash -c "rails s -p 80 -b '0.0.0.0'"
    # command: bash -c "rails db:migrate && rails db:seed && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    networks:
     - principal

  db:
    image: postgres
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: growth
    networks:
     - principal